apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager-prod
spec:
  encryptedData:
    api-token: AgB45G7m87aeuN0F/S0/UzMZkh3TuwqPWtG6rAfZZC+VCz0IBsgCQNwRdkAz1wx+jchcOwl3iS5PtIoAB/rSIfERcMAXWDEPO2ypPv63tZBf4AQwwfPkd7Pxa8EcuRjboTUaRmfUD4n5NK+MVBVfvKi22Djg9WJacmm29xH0F9cetiCie96uPGQ5tgPHKcV2iNcq0Y7nQ0VkWulWtGdFkrK99EVWti1GFKe4uVGmGaItIWQMUjg/yY+9u941ad37Z34lqPc7Npeq3oUfmN1y5hZ8frFQ/dlKlQIgfGy1XDNDMVtJKkzIkn2DlNFqgfigDUBUdMGQwm8W2FJWwczRDSR+BnGdWJ0F1S6iEnRdNoYntibHVE1jf+J+wW2EjhZwbT0rMPI5QRI0w+vIbyOdsm3oA+JT3it3PWbYee3mimmr8cRtfLXucgJSMocyill0OisLcr7hjCiNySgJ3o0w2uI6yTxsC78K4glF9BiDfz1CKsWR8xyQYhCbcsV2MmMUjJ9CuqIbrvkDGY4w1rUCkC2SM7coWXEEOzx1vy+9torr9eZPIIE69FZwegHxlgrV35VTmRTrWR02eGDDfWn80GTRzclVcSpMlADcAcHzVFqWa+2SpfDG9YankvpVP6kT6+NAzdH85JiAJ39tX4N+eXCcVpDCSB7UwUITqudDUWuZ0CpFFyCg2UGYeijd06z9IxkZhhv3T/CmNgvycKNI/diqEJhWWrx5eovbCpXfZT4cKU9nEuImCIZ3
  template:
    metadata:
      name: cloudflare-secret
      namespace: cert-manager-prod
    type: Opaque
