apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgABx+jK2hnCpe5BxxQteIJ1Z8/KhOJq4bAQC1rLRy1m5bxkg6v5YDiGICC3dysdEHVOwXfweYvbr2LVhBxl9jOWuZ7NDflcn+kjHH9pGIVzGAr0NbISBaLVH9tBYZFEZ/Pjnonjn8ZqZi3JF4ILNFVD9Rw8uLhu4FBIFeACEpRRyWfrKQa9KgIYdTy1eC3fLocKSFYmmhccjwmo7IzmkU7JirsVlgMAsL2DuByl4YQqyfXWP2dfVEShUIYiCaaPb3f8MAETumZggYnQ1YIEsOBtj5Jnqyz9OmrZTD7pgLz9UGOXY5beX25GCtgvaYsazri/DEM9/mSh3ItOGg8F+uVf5n4GtB0VriPysRyOIJoCki2LRhMJKLXxKBMMGEWhVkvfxD42jd+gtWMrCqZ/L3fftNMBWUbZ/oD9hrf1Jlkv/ecp2vH4WQ/V+HlIgxRUjCi0txPDB2ebR/DaSXqAMGrk4nV11Ovg7JA6KmWTZ5N5bijjhZXFn1Ue6Y3JLGuKdb5rr9cpQA4b6gFRej70GstRt9bmPROYD6fndml4dOye0R+pfLSno3mDHwbJCYS7zIpe3KiuSXfy9ESZLWHF1X9dhOo7tQHlb5UUAn/PZrWv7aCMVVnOGGmUouoiEzQlWPUtnCyedyRZUSsAWDDSACzrRQWk8JP9FZBm2zS7SnRrx4rlspiEr+clbwFUvWT4npyxi5NwFQPTGKhi6A3rZRVJqOLUfxOk30gC3p+85ZVXS8InVha4pljy
  template:
    metadata:
      name: cloudflare-secret
      namespace: cert-manager
    type: Opaque