apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage.yaml
configMapGenerator:
  - name: homepage-config
    files:
      - config/kubernetes.yaml
      - config/settings.yaml
      - config/widgets.yaml
      - config/bookmarks.yaml
      - config/services.yaml
      - config/custom.css
      - config/custom.js
      - config/docker.yaml
      - config/proxmox.yaml
    options:
      disableNameSuffixHash: false
