apiVersion: v1
kind: Secret
metadata:
    name: metallb-memberlist
    namespace: metallb-system
type: Opaque
data:
    secretkey: ENC[AES256_GCM,data:h51FMLjcNed3n3KbrN50/30lNWJsNnQRUFDclYq3qz1BevqT1CFVScTHW0ipAnajSV/PI2edNcd+p/1fRIOU6+tr4/I4fzP9Fu4e2ZwKbBXVJaDouWfGCRdeDK4/NBFdk7KwLMGS7W8I+wwIyK51hCTQUNteyoWLyToKZSplS0x5BWP8DDKoJfM4CLmFzgUf5lpwiIiASRenjGDVoI7Y0pDC/AIqqUCiXdUM4/lJtEyY3IZQ2CUjctZbQ5zBqCuZJnXwM4UkLshw9ePJtlYsGWf4rccmZvLyCWCpQxvUbsdAvQXHqKuiRIPGFBpjSVQqqwFB+kXODArl+MQWlVu8ZGdyp4gmgVZDGKL/aXxUT0m/H869fMXv0MSOL/c0l4rHp6RrVdNEuSiLhOqDW8tslu3+X4Iyww9yVfAyisGLXll42xyayswzOElqZh4RUqnwkdJwag1e+WU=,iv:F79I6vn5tCa9DkmkGqAVlbGnBNnZufFoRIotYFJzNqo=,tag:G/M17FE1B55T+nX2mdr1DA==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSFA2M293TGdvZ21sbmZN
            ZjhDVGl6L2tMWklDWlJjc2hoak1wRzhPL0hBCnZwOUFucmVVeTNhd2Z1KzFPUlhQ
            QjlUQmRFY05MYkxERFhtRDNEenpsSGcKLS0tIFRLdFRsaDJ4d0JKY21DenJZMjRq
            dzF5V05nNTdrZHRSVWRuSnN3OEpIMGcK90h3r/u0e/njE7ypk5qBHVrapAXjKyRx
            T8W/qmQ/k+MtA/45IMmxM9pC9NOK7aXR0zXWOOU5aHof5Wl0jJAAhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T18:52:13Z"
    mac: ENC[AES256_GCM,data:kTwGZBg3O1QIuMsrTSj98gtJwhQMCCOnTGf6NHzZ7Lub4fMRRZ38PAl8+1A/2+gKGjXIOLb1LiPoVZe1pdLy7XNR/2U5lZazCgdpjBQ62E+1CrQFzP2pLmYs41FLluwMms+TlooUwrAdf9x8LoCypubuG7tmqMZNLxMVbCSF+d8=,iv:tkg89UvYZvgkri0mMrO/l5P36JlxbBoOMXSQJi+vEgI=,tag:TzyzL3r0dltxd6xhXLMFGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
