- Developer:
    - Homelab Playbook:
        - abbr: GH
          href: https://github.com/ksiggins/homelab-playbook
    - Homelab GitOps:
        - abbr: GH
          href: https://github.com/ksiggins/homelab-gitops
