- Infrastructure:
    - Argo CD:
        icon: argo-cd.svg
        description: GitOps continuous delivery dashboard
        server: argocd.staging.lab.supermorphic.com
        container: argocd-server
        widget:
          type: argocd
          url: https://argocd.staging.lab.supermorphic.com
          key: {{HOMEPAGE_VAR_ARGOCD_API_TOKEN}}
