apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring-staging
type: Opaque
stringData:
  admin-user: admin
  admin-password: Nd3$5vK7PeyyQ7*d27r0#XkVX2gE1BAzzZVEJERA

