apiVersion: v1
kind: Secret
metadata:
    name: dashboard-auth
    namespace: traefik-v2-staging
type: Opaque
data:
    users: ENC[AES256_GCM,data:P6eE8GrcqYd3TH9FhBLNNk3UfUGUiFVSRKyu8gQttG7iaVs8x93Oma2Arz4WBaK80xDuKPYb3sNNNTC3,iv:zk+1UgxcBKYv1TQblgFKNd1lLYx7sKDKAwCVmdhfOK4=,tag:QxgUSqgZ+qD3fE+crOKkBw==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNmpITTEvcVIwY3Q4TUpI
            Y1NRTlRDVmcyVCsvaTdsa0NHTFNmTENhMlFVCkdhT3h5cC95aHR5UVlnc0N5ZkFS
            ZTJwakc5SlVDdStKQTI4UXgydm5mNHcKLS0tIEMrNndMWUpKeUtmUGZkM2Nna0p5
            ZXo1WVk5c2U2TVJYSWlnSDY4TTIvWG8Keb8DRVeaxB6QrtBSV/+I7Tf1xjjxCz30
            fm4MGdA0AkPkNh39SJQce6OxRUxUZvrvjzk8DAc/cJl+6xoOTPD8Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T04:04:50Z"
    mac: ENC[AES256_GCM,data:PRUSWvDKzUmpj0jBC07ubJHx+T6lDXrRgauaKXqleE+BBXR3V0S1ABLxUC8W94rDeZrUOqW5WoJn7lQ/CorgUCZgoEeWE2PlMKhS1/6o/xnLHnAoREvEw+ofNgH1fU2thKdHnlWhUV4kS4mpO1LKbNy1mCsX1/4kEA6gLxiCgmY=,iv:X+Cbv0DRuiJrJ0wSbIkINuZJJmNR14+ZsIlYBR5ObAU=,tag:M46TPOTGaFVlvf1GxbmCiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
