deployment:
  replicas: 2

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    allowCrossNamespace: true

additionalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--serversTransport.insecureSkipVerify=true"
  - "--ping=true"

service:
  spec:
    loadBalancerIP: 192.168.90.102

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
