apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring-prod
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:SodBSRs=,iv:x6NDVoZ1oJ56PuZXUn/7NDy6X68E1V68nU5hWFPQEyQ=,tag:cE+UHethXb7TVVryDxH+1w==,type:str]
    admin-password: ENC[AES256_GCM,data:Dj0UqJfyr2AVC3gOtR4qzaVpJLHRcs8vIfCex0BQw4EAAucgu64T2Q==,iv:cg3lkfrbinyp++OXAg7LIiTyvI8RitLpCZ7Sat1qHhg=,tag:ckR3fEI2en5YwqcLV+ZMMw==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUnNLNDRyZXRDaGE4V1Vl
            QmVZSjJ1NjRMRVNLMWZDdFNvS3g0eXpJMUMwCnNQRS81SUhlMSsrUFdERDc1ZzRL
            RyttVjgxK0E4dkxIU1pESWZNTmVEK2MKLS0tIDg5OTNpaEhCUHYvNkwyNDZGbndI
            SC9kaHdhYXhkNW5RQWc3R2RpdGVLY1UKPz+jFQWZaUUlP+JRHBGwrRtPQkIvFLoH
            JB11v/Bk9NzDiSYm9uCKV4aVI/T9Ct2VbZjLz+t4obOdzYSv/EcVZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T03:37:11Z"
    mac: ENC[AES256_GCM,data:1K2rvXjs8TBQR4wEE2+ibn4MQa02ondwmzbEuf4HngW+QKnmdR0k8FefCtTgl9x1Bc/Y9E/SIYB5ZNWmsZhqvTzXCr8J+wGQDFfERP+/cLQDvU5Nw+f4ot5FRwzyRrmnSuVboeVrnIDguOK4r9TbJxJcnx9asaNRY2fkwHESCKU=,iv:vzGAUF4qM4RXFpWqqSaUsO0qMbm8hdz6vM/SI/x7ve8=,tag:H4CB+V6eeOmxKlACwiIKXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
