apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring-prod
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:PfRR6cU=,iv:nJ2Kky8nTLySKDQCl7+8KHY8uqkbcj8ep2xz+0w8tOA=,tag:7+PaJzgmiayWMRollVLHBA==,type:str]
    admin-password: ENC[AES256_GCM,data:oUuVUUacpMS1r+BXdWdn2s4B5ckE5TBbLdsmh4noxe7wJ2EaDK9mYg==,iv:+C9kQH3rGVFelD3TNFU9nzASUy9+XiZJ3TfTp0qT71Q=,tag:tR5yflS8OUFCKQM94G62iw==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuczU1Zm8xTnpCRTFIc3lX
            ZXowMTNIcEIvTVE5RDdIMVZsN1RlU2YvZ1dnCnFQUGpDN2JRNlRRS0phNXdabXdL
            WDBMNlIvdEl2MDF6NGZRQmNtWWJ4ZlEKLS0tIE1UWTZWR0xLYk9zZTBBOStzZ0wv
            Y0RoNUJ4MldadVFERGIzTm9rS3ozT3MKMKSBcv0WQxx2KCxYuuN/ByzoC7HMZmrl
            RkkF/hZZ+Zk+OGTgfghIB+a4kOZNLiYYD2f6XXmuMY0PktdQkYaj5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T04:00:04Z"
    mac: ENC[AES256_GCM,data:rtMVnIc6+FK1mvKObdFto1Ga1zoueLU2UfqoCphr4lHKiZT0yUrYfYXxeOF3doLyVyohboh0aEt83dHrsIqCtiVM1VNiwJdTPTaPzk3NLIMcYkt+pGxSH9E2aFUpPxEqZq3zMRVjGpj6Qvr0b5hM9uB4RFNxtFEJ8n1v3uRwMDg=,iv:WX2IlAAprmGlaQLQuG8QqiXfU7dCm1hR9t90KQTEGD8=,tag:AJupjbR4F0RYiPh8KFT7hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
