apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard
spec:
  secretName: traefik-dashboard-tls
  dnsNames:
    - traefik.lab.supermorphic.com
  issuerRef:
    name: letsencrypt-dns01-production
    kind: ClusterIssuer
