apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:q/jzSXuJUfBKkJQbcfwelL2uLnvrV5Z7Sk8WeCRqrveGwnO02VjQ2g==,iv:/LUM5RZjgK7CXc+sAJ1LYjdC188Wgs+R2X8Q8DMW8wM=,tag:8zliEYo5ojdrmQzBH6eXjQ==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRHVLMGwvdDIzLzZONmli
            OXZNU0MvVzJGaTRIQmVWR0w5Z084dFZRL2lBClNJc1ZPUTFoU0FHQXd0RnFoUDJl
            UjkxUjNxaWtWcHprS0RYOHNNdHRGNWsKLS0tICsrbk02UGh6U04yaXFpR056MzBL
            RytkVjgvb1N5YVNmL29KeEFlTHBjVGsK9v8yMlizaRtHHQX3cxyoD0Gc4SHv+4Fm
            iPZSD1F/GIvv8USWufCsiIOZQKHH6aIWI29rBU0cK9yig0Rv5giJIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T03:14:29Z"
    mac: ENC[AES256_GCM,data:VRyEhx8UW5pPQk2oFqI7Y8v5cqncE1hq0HXh1aG5mbmnp5iiLCq7StaywUkDgHJRe48REuDoW7h3F8K9MLQOFkLQ6ABXw1q0s3htlL2GnU/WyM/1aQPhUxlstH3CPEfDqG/IdBc2VREyqKn3A+OdJqqCcYhSGLf8G58csDIEObk=,iv:6AHOPB4+KdNZ7t/C1TczPQo5xiFPWoT5KbHw6k9zuUk=,tag:z0HHBtYXm1Qj7pwxiVa+yA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
