apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: kube-prometheus-stack
spec:
  encryptedData:
    admin-user: AgBYQiXkvi3YYp1hEa5NnC2OFQYUpJfllG+ziQNWmo1tBdmLB76Jovooyj8m9CMgAAIT8E1Lx0AD29tbyL8VRHukHihsIUMPRRs6JtIz/ikHTvGtzPZDnkAcHnP6kNgeu1FMOCYDeNf5v9G+MuEkrXQs0mGIpX0YEeITpHeXv3Vbd8H5EaxRwiTYZrRDQAzeHnY+FQVxZVmshb2E354Blu+Jo5CtRN+TVYwZiRsSt0VqxG4u/S2DlNXYfS+pQn966Tciv6W8gH4pD0yxst0NwniDzWyU9e54AVXVFddqaIhK++LqoDbRxQBm8wkBzmcJM0p8wgc9arfB6fsO2J136adBbmGq7Wh2l8kdukc8uOkKbeJAjNNxHThN6JjvG8U9l1vsAGlVgcn180EsKKIWB0U8Nm+3pVW/NSxW2MmheMnnhnzG9vDTnvpHfICCZ7eT2AUeJG8WkFVq68+y3dK/oOlL4tZu+Uyt5k5wqNQSZY2ikIk77nsyizZprHFqHYojk/BhddzrDbJg61j+35eKIQ0yWmojT7dbPwa4QVZG/GmkO7bX43yD328Q+LWbYVsfyATzyk//PMMmYorE41KFq3BqYpJLvi3XKPQNMImvObxlaVcQk5V9bDVQzKmEl/7Xpyj4OrbtVf8/4oEC8jj8nncTvX+Czr3m3F1lN7B51qMcXgn9yM8UT1nxhqyPy3HBymb1MEAQKg==
    admin-password: AgAQGmqNpRovRD7zPu5mST51KE5B98mTQQt1yQVybZ9suv3Hp6AQKl6+sHf3rpkj6E5OvXimyLbioMlHT3fpM7ujw+D2xejySHhDY7WPCAZHEh6k3EJIxQeL39iz7XOQAbIsNx/J84OUUOHaBRRqm28q2hN9byrnWc7eXQG2iLqFyzlCWEftp19PbpJ8uDXBiBYFLkR/PZkVX9GgndIQCq0KY4FGlDoQOvaE+99IHCdLYIxB02cYPdgurUlXH7NQWnmDQShSeuKpudyqYFzrfbnOQ1jzzH5FOhdQHUBjoNDX52rHM4ajGL6f1DlqXoiGdcL+g09Rc4Bnu6HtNilt+bvs+ifmJeooKVyeXOg4ct61ck6O1JdHU1zue/zHJ4j8zwuRFmO3Ij+mh7pJ/Drb5jNb/Fpfej7eouADp6C16Ltob7y7VP+j/nO+FNNPGfJW8ZVlg5SJU9/x+D1+gsv91K1tA1KL2hYCAmJlRccWg9zt5NozvfnsxisjStwWa0tg1iT4+O4Elz7sFKqyh4EGtyn9qdxujiSDvVxxXSr35Lro8QN/SCB7nC+crEydz83DTivAl83cczBmr+Cp1KF27f6Y8T0vPY+mn4cY1Nb/AIWsJQUn9FWXcaGsLnQuSxPGMU77U7d/6h4J4NCmtKDrZjg9O0Zpeps/3I8uXTd5zPYVUbPwBu+pd7+RM4oiAuHqux6ZZoCxGDsvx9EZLcnzsKW7QUqxvoYNA1nfDJe8MBIemTd0Bnt07I5Q
