apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-basicauth
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: homelab-gitops
spec:
  basicAuth:
    secret: traefik-dashboard-auth
    removeHeader: true
