apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: homelab-gitops
type: Opaque
data:
  users: "{{ .Values.dashboard.basicAuth.secret }}"
