apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: traefik
type: Opaque
data:
  users: "{{ .Values.dashboard.basicAuth.secret }}"
