apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuer
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-issuer
    app.kubernetes.io/component: certificate-issuers
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: cert-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ksiggins/homelab-gitops.git
    path: manifests/cert-manager/issuer
    targetRevision: main
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
