apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 79.1.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/manifests/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/ksiggins/homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/ksiggins/homelab-gitops.git
      targetRevision: main
      path: manifests/kube-prometheus-stack/overlay
      directory:
        recurse: true
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
