apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: ingress-controller
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.2.0
    helm:
      releaseName: traefik
      skipCrds: true
      values: |
        deployment:
          replicas: 3
        service:
          enabled: true
          type: LoadBalancer
        ingressRoute:
          dashboard:
            enabled: false
        globalArguments:
          - "--global.checknewversion=false"
          - "--global.sendanonymoususage=false"
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--entryPoints.web.address=:80"
          - "--entryPoints.websecure.address=:443"
          - "--entryPoints.traefik.address=:8080"
          - "--api.dashboard=true"
          - "--api.insecure=false"
          - "--api.dashboard.entrypoint=traefik"
        ports:
          web:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
          websecure:
            port: 443
            expose:
              default: true
            exposedPort: 443
            protocol: TCP
          traefik:
            port: 8080
            expose:
              default: true
            exposedPort: 8080
            protocol: TCP
  destination:
    name: in-cluster
    namespace: traefik-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
