apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-overlay
  namespace: argocd
  labels:
    app.kubernetes.io/name: traefik-overlay
    app.kubernetes.io/component: ingress-overlay
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ksiggins/homelab-gitops.git
    path: manifests/traefik/overlay
    targetRevision: main
  destination:
    name: in-cluster
    namespace: traefik-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
