apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cloudflare-dns-token
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: cert-manager
spec:
  encryptedData:
    api-token: AgCEmsLN1IOzle2RLjIk7oZI0i6bfJczqixnLOVSC7qbWepf+oSM2dSOLRN1pymDiwIV73ki0yaxx7OzG1H4QoiLP5xKtvITN1/vnuf9pKhRhb7hnCwjICtt8E/WrNSqXzMcdOx5hSpnc0VQwruyvFD5/c7IivauDAWtuORqwaSCqWzVyKQu7h2Kx/8ih3xj84Z97qi3KHTIdvhsP/7UQNdHXvMVLnEoJYM5SnK7oPrHSDdikoxi7vMA9PHS1bpOVL8Jaonol+oadcwprCSFmNRy1C6CcKZZQmLQTGCYj/pUugJYAOJAF8sPWl6YRuzLBt/UHEkNuE7YagdGbAdhEEhqwwFxW7tLLYCB6BjKWqWmi6iDP551tLja67qQMPp+8iSWvBSkD4ceZwuguwVC79LI+cVLGY7w84a1YefIobHNFn8n65AwrWMPC2B0ZUSVSVtGVIW6cCKB/Gac+thI+qXGJZpMJp8t9sAXJ/my9gGCAvV8/rXsh1cWCnrCeg9h82jYjEqfPfFg35BvBvbb1dJibMi121xTprD212oKKFeqJ/rjpd5rHh8W2o53uUwIuD/VfynTBj83PC8bjtgHgegWOxKsjTEJ0+3571eWPJzzAZRmcTUEmz8NlasZmDbgL9bsL1hMziOWow2qkr/QFsWx2r+Ibpa0toKmncyLhUUNzWNeq4EqZg91HuBXlqmA7HEf/K5kjJ2BCn5q6Uphof9UO9c2ZxJnHoNZ088um1xxX7GMHgl+VzTG
