apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    api-token: AgAIOq3NKslm1D8cIOa5xfLIyd9Trr6YcKue2QOT8D/6AfrJVo7/jNWTRBYM/tR69UhTxbGBQlOOf2oeHm9A1tU46ecXgydeCxYGhDscannJQPzMaDiZYEul7mzjXGosgkCJZ00z2hCPAJJysk0VMo1WpAyaxqI6783b1tsZjNxBug59tSwQjjgYVa/cj4EzferaPODThcx7UbSn112nKyRK204Uz7NAjnrIjJVs9cKqgn9GNRC+6Wa2c/pBYnF/+nJ+XC+94sIZ5V89aC4PXqlaHAmBz8pBgaIA2lwdxpb/rmw/hHut7AOLWGQkrPzpv6v3ebyOkbpVaZKNWkYhamDHq86gKixMgXENQBgBN4+zG0AgyB9OuAO6lU6dPsadvLFfP8W5Jalqsssp8f9T+p3iqexX4u8R1hu+trqrTNSiO4CP5OrKL0O0JEAGbv+c81/SPRS3MpWPd4u6bTqhu8c1zQpChXOtIb6sq3YkkRKZihHfOG51lNVFt+z8Sm8REhTL2OSkB+Ht3vNbeP/Pge9bV8d45bg0Mg4cduGt9doFqCs/qkkD00TzqDKxeoJE9t+4qoNaZYOeDEUoy9zffV7PNduXvJykovY3M6qzUWpL+3mD5IC2rC/sw5iGSDhoh1MUqIx8cvFkTC/OTFfIZ2T0sOrdI5/wTlDaNiViZyW7a5m1jDxYklzq03zExvmaxf6X+5iEr2EjIfnlEt3tD/zx7yOHk5HM7tF64gEpW9+cA/I1pPgbfZ22
