---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    api-token: AgA7sR7/scF+4kiUYM5NyxsCQJElzq97SLsgI3+0BtlDeahnmmpLMyKbbFyfWaNVBvY5jiUwRTL8K832hVMzxxFZjsjIOCxIKlgrndkOUMGXdqkHxk4hUfDlzI6IkzgWuO86DLTvI/3U+zd5fTPv8YXInHIwKbcHTPN9k03qmHpLZBYv+6iYMGaUvmVSr4A4+1wvgW87lMdGbg/J+3mXyFNtloB/fz4JSd9BY5zOyWpWV1laUBjcO/PWt0a3deNhbB9hX2f2V+TYEuNj+uNGmWPeXMrbCdr1fEtYpsl1gsiisRldPihE5CprTSrUIMxnsMp907w5R3cPg84u57gZ8jUhvhH9MoOoUbA/tPSmYpj909VqSoCiDjcwqX69Z31umkvv4jzPdboSNjPezu2TiunQ1Ptxm6PxUFARX3hFDY35D6xFqwwtUJ6xe4VEfcrg9VCq/dJ+nE87fHxqmcJquq72ZJcs3sKl6SbggP9Hka5RyS3nt5OO+mKIvDR/PQo/GJFg9C62VhMIUlAlkEbb1UAbxbpm46v6HutT0H4M3Hux7lzaw+e/t0tnOQPRr0OAyZHgV0PYp3GvOmnJWkSRosPIUCP/aNyOvllJcdzvLH2RgJ1mMppWHQj4x3GSj3N2AUTqLOd5HHL6EMsJoIGygMY0pH2Dw0WtyQieVOd7Fs62q+GSdWJ/8KYp2NRAcJztTDSeb5evDXVBwNMW5fnFQYOGjM2cKBVVACMjfOnnjvbDvc0eszxAI08f
  template:
    metadata:
      name: cloudflare-secret
      namespace: cert-manager
    type: Opaque
