apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cloudflare-dns-token
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: cert-issuer
spec:
  encryptedData:
    api-token: AgDK0hoZoRVC96eOHzVoLjOOpOkyG0+HKDHuuBrMwQSoL6/+sOzVXP4FVuswWIO+GLmpRH60SfkL5i37TtYyEtYCjQ/y4qtdhD5l+bIscItaJ14nZLtBUYGFdmrQQy7NoSHtbqvejXw++XHvyr4ifaRFGomfJ5t3VidUGDbHnQKwRA47mOp92M5+yKC1Pj08p4a+/JTTxgnBrTp5Pti9Phmp1d/Mu0OoUS5lJPTiZVJSSS/kLyABMbPZ+aQ6+O/v6s1O8bxljZznqUzUikAZoCByQ+lhNE9l5b/ztrrM5hbS0YnIAv2z9mEO3KIcC+keJASnhDSUfkiE4wGSZNu52EceEyrSzBQSD2CbfJIcxOXC0ysLK6s/68Ocdx0zrmENziLTxnn72FAJ8kA1ESZCjRHLGyz7RBVDrvOob3Ts2gQc68LTVgo6O7GmLNtUVulLaIRrBuJrgg469sCHH+0dEi2ViE7PVUEbGx5TFEQ4pEbq7B6r8Nb4QsmXcS+w5XIWyfbLqeiVb2HzAE67IGirqcnJc+VE/9jlQAqfyrD0eMl89i6+nfitnTElmtXFgzGroCfGtBvD67ogiNwXxCMB8317HumjHzjP7feEeRNsM2TfWKBAacYI7ImD1gLHjFAAExtMlrhxq1PihSEBD0FUFr3JPAGpNGmZCFn4hv2ZBy/DCaRARxytamcS8phcZsNZ762vrSmeEssFFNhF+tcFTK+3La7qctdH9b8TUwJp8M9hgTYvoXcyA6/G
