apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    api-token: AgC1UMLaNrKRjfWOwSbKSk3/X0V0NAVR0LclCHOs2MCtzEzGrywkMbnmqYlSQxFck3fujhYSocodBDChttw1tf/L5aYMycDO9Y93+C7N6ULyc6MmC23nbNl+qBp1ZPE1FbI2XPkLs+LagpgFLEnDG0H/lnrWTnrjNFU3ruyCdc31+ycNTNADEt33uPkygS5w9oxANaCdaIVxJSxHUAmy6fVYmBZ7zmyh+CeqKuLSiVLUdQh69CwbhEgzAqCyrc9hGzGFKLKEWa5v+cDxSoDknQTTCukzgcTJIN3GLrF5BP0rw9oh7x23LPgccP1WVeM7ETpTfvts39eZ4bbkaOmUcklvou6dwODDhK8ev2jSNxp9s3dI9t3V8XWyBkkmbGyhTiEmyLjXi0aStmE5/+uk6zISEevO+qgfh2SgPLkIF7u+/J6Z5RwBKDjcUEWUfFe4ygvB2Xj43zl86T8od9ojI3gfyjBAyNLFwSgfWt9EGApqNlVT+ZiL0bSchTQU5FVzjcKpGutZYxfwTtrylZsasvnsE2BlnyKZmrAnrjd6bVoB8w7EWx4YVQJycGRqgazj041NtJlkvjdpeRo4qIqmn4qSU67F6ZGoGpWZjrVaUy1KSymmTySbRiPRBJOkTDQ2mrSwVlE2XhkP2OBCjRJV/mlUyuq9451ysLdv3KZ1xLfI0gjbamEonABFSIkzPoB3oEYeufMbsUUIjb7GmQaUU8hNJzTJlpCIACil32bTGF/e26v3GU5c/oQ7
