apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik-crds
    repo: https://traefik.github.io/charts
    version: 1.11.1
    releaseName: traefik-crds

  - name: traefik
    repo: https://traefik.github.io/charts
    version: 37.2.0
    valuesFile: values.yaml
