apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.metallb.poolName }}
  namespace: {{ .Values.metallb.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: ipaddresspool
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: metallb
spec:
  addresses:
{{- range .Values.metallb.addressPool }}
    - "{{ . }}"
{{- end }}
