apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.metallb.advertisementName }}
  namespace: {{ .Values.metallb.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: l2advertisement
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: metallb
spec:
  ipAddressPools:
    - {{ .Values.metallb.poolName }}
