apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring-staging
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Xo+m7CI=,iv:9+qPq2U5ugOJt5HyhfGvLRfoHeeBVxquptuxoeqviDk=,tag:bcRP3FZQqJ6sweFZsso3Tw==,type:str]
    admin-password: ENC[AES256_GCM,data:K5GoS268Q436mjqV7lh8etsyCstCsUDhpiiCveNn4ZTeIzoBRRzjhg==,iv:dikem/cSR4s5bCPOAQQSMxljvp+aPKErGJd62nkvURc=,tag:+L0du5ry9tvhWtXAgvRWjQ==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHK21zcVdGLy9FUWN1Qito
            M090QXdBcSsrMmIzRFN6bmNndWIzSWpYSFJRCkNnRmd6VnhUODVrd282Y1hhdFVn
            T2toSHpSZExIdTE1TWtBZVVKREhWZFEKLS0tIDRPbFBEMVBHbkhucjYzcjh3SWJL
            V1REV2Q1UnZIWVFYSTlheFFzbFh2VXMK5PzMTRrWErsDM6GwkdBt9bkpZ4lCP2F9
            b4HB9pWOXgwN4KHBdCwsuWkTcjiaT73zp6gm6CRBRItzzxad2Y41Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T03:37:31Z"
    mac: ENC[AES256_GCM,data:SatTxLvPspX2ehQ24ZSG0j2elq7aVdCqOqOnATLCkhh/Vj2OWIpHxqRgfmc9Q2CwiiPu2b6M/Zt6A+ZQI2a5WiFzCxPV+UxUQXJu+qtTEz64I+Dw4vwuEcbjX21cg2edfYEqvjheMT+Hi2H6r1kgIv2pSFCZjL6GmM90opXmMxo=,iv:Vg4qdJ4ssfURwtuPbIAM3YZQWPhX33bGBxNiHV0URhw=,tag:zgPPanvLgj2y9ZGmamMF1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
