apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring-staging
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:1PtHa+w=,iv:Oio+tzbF95d2m/a0XpKyfDxRtkuzSHsoZXXGWKtRaP8=,tag:6D7f97WMZJgs5v2NP7BoIw==,type:str]
    admin-password: ENC[AES256_GCM,data:vk5rQOaIQmQ2T3+0BqJj2b85KD4G7nOx+S0woVYe+kn0Nm2N2G48VQ==,iv:4WHveVvDG03s9fuPKV1gbZgWVajkMJAC/o+JGJwQjZc=,tag:h8LYGcyMGQM9uziGgNglDA==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTGcxQnZJcDZxWXo5Tys4
            UXQ3K0JwNWFJaE1ManB6YWhnZWNDbXNaamlZCmo2RERUY1dJandneHVsSGZQWlRH
            SDM3TXdFTjRFdjFNNE5TZDBHUmsrUHcKLS0tIGNRNzAyb1psNDJ4YU5IUEN2NzN1
            SDNHU0dGZTg2SUpsbWxYajJYaURoc2MKo2C/0vNqWJVM0qf2ljZwV1kRMI0/alug
            hdzdkgumzMHE3SDt+WdOcXwqSp+EoM2fwq9YG8jfd6/QmG9bdjNN0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T04:00:40Z"
    mac: ENC[AES256_GCM,data:p9WD5eV0AZjBHljQkdjmgar8c+oEGYX99bcbeZCW8DAC/4+YxX5pSfoBi25tE2A03oMVtsx7Gqh3H8jF9OcV97fS6G0k/+JI5cNzvM21udu7CnCM4+vzWwe0Kav2ZM8I6sjcyS8oQ6ZgbVAFdreFFttfimDVOWRF3WfLoJs3hOI=,iv:1ZzUs8/AyN7W/wodOdDLBlpyYnWx922ph4NAbi+w23g=,tag:jzw6FAJiZCtaTRf4OJw9hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
