grafana:
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: 300m
      memory: 400Mi

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: "8GiB"
    serviceMonitorNamespaceSelector: {}
    enableAdminAPI: false
    enableFeatures: []
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
          storageClassName: longhorn
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus

alertmanager:
  alertmanagerSpec:
    useExistingSecret: true
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          storageClassName: longhorn

defaultRules:
  create: true
  rules:
    alertmanager: true
    general: true
    kubernetesApps: true
    kubernetesResources: true
    node: true
    prometheus: true
    network: false
    etcd: false
    kubeApiserverAvailability: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false