apiVersion: v1
kind: Secret
metadata:
    name: nas-credentials
    namespace: longhorn-system
type: Opaque
stringData:
    CIFS_USERNAME: ENC[AES256_GCM,data:V2pn9yZlIcE=,iv:XgTxvqwazEDZ631232lXnjcrmpwVCdzuTlKwc1SwAnU=,tag:ucoKBnig9R/TFClBJjfUJg==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:wTjE31ftlmZ+0cy81sHQStXZIPQ=,iv:pLiVcsTPdbsn1TCjRs5HBRA5UkNQdEkjvkbeW/H3xow=,tag:qeRNSf9vLGOxI5dSiKfjvg==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dzVsblR5blMxbzYwcllJ
            dlpSbzE2Wm9KTE82aXNsbkFraG0xVFUxVTMwCnowV3I1QU9NWGl5UUgvOGRtaFBq
            WTFremtZSEdwSk5VYm1LZ1IrNnd4TU0KLS0tIFd6M1dkYXpGSy9OcXpUTnhVOWpy
            azNZNm5YNGVvY3VFQ29WVzdVRVNsb2cKcbybq2kkxe2PwwjaZ82luxy/n9YzEBBt
            XNitdBy5i0V6abUMCOHZ1hDigsTYVXGbfdnu5rv0RKzl4mWqjzelOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T03:06:30Z"
    mac: ENC[AES256_GCM,data:5/tYkEDFpytk2H54uJlv5pi2I/aQJxGa5xghAVfHBi2ABfGV4yEi8deoGqgG3+01VZTk3hlIiolLHOKYrVJYdr4b2tZQUFGkyfwOSfYHa3q3+LeWAWuSKu6k3kI6M/YlOAHGdx66l8KL4MiMazCCQCXIOutQtue2ssTK7qKb6e8=,iv:JocjT1PymAJaoWhETDjvOHo0ilrKbxgEqRjiyDfPLMs=,tag:wxZgEElV6OqfKZVrThuJtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
