preUpgradeChecker:
  jobEnabled: false
defaultSettings:
  backupTarget: "cifs://192.168.0.3/Longhorn"
  backupTargetCredentialSecret: nas-credentials
  snapshotDataIntegrity: enabled
  backupCompressionMethod: gzip
longhornManager:
  tolerations:
    - effect: NoSchedule
      operator: Exists
metrics:
  serviceMonitor:
    enabled: false
