apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 79.1.0
      helm:
        releaseName: kube-prometheus-stack
        skipCrds: false
        valueFiles:
          - $values/manifests/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/ksiggins/homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/ksiggins/homelab-gitops.git
      targetRevision: main
      path: manifests/kube-prometheus-stack/overlay
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
