apiVersion: v2
name: traefik-wrapper
description: Homelab Traefik ingress controller and dashboard configuration
version: 1.0.0
appVersion: "3.1.0"

dependencies:
  - name: traefik
    version: 37.2.0
    repository: "file://charts"
