ingressRoute:
  domain: traefik.local.supermorphic.com
dashboard:
  basicAuth:
    secret: YWRtaW46JGFwcjEkOXZsSUhPNHkkOXBQZnZmcXQybmhJNi5qbVREdVpKMAoK

traefik:
  deployment:
    replicas: 3
  ingressRoute:
    dashboard:
      enabled: false
  globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"
  ports:
    web:
      redirectTo: websecure
