apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-v2-staging

resources:
  - ../../base
  - auth-secret.yaml
  - middleware.yaml
  - certificate.yaml
  - ingressroute.yaml
