apiVersion: v1
kind: Secret
metadata:
    name: gatus-admin-credentials
    namespace: gatus-staging
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:e1uMS6k=,iv:cnAYP8ooBetd3Tnm4jibJKWLlT2rbbeqtbDJoA3oRiU=,tag:2FJiKA9WWRTcxjxxK7YAnQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:HC9hDG3AWN3DVFJrfexS346H2erC7eY1ku3by+6mjjFGe3Vidzh8Eg==,iv:+jWgKxzPvjNFtJMXanV+iLQhhxQhM3Tdf/Hzn2KZ96w=,tag:0rqolHn3ymQuOENrOF7LEQ==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TENTZE1qY3p2RGZlOFE2
            WUF4cVU3Sk95WW5HVUkxajRrNm0ySTBmenk0CmJLaFhPWi91aWJEWXVib1VRaTU1
            MnorUk8yYWJkUSsyTTBMTDFTaHFUaEUKLS0tIEpKUFFZc2pNaXhXN0R0eU9oaTBS
            Y1JZbi9CRlhpeC8zQlNxaTVCMmVmMncKBltvVLEcQffLFtOPxli4BtPH4f9Wgzc1
            O0H+aZpEkdS3ZOZK5Cp3Kl00i7jtlJpqwovqSqYaXkLdv9yYmE7CPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T04:02:45Z"
    mac: ENC[AES256_GCM,data:S7XKNdywjfmHtJ+Ejdsra4lROoIN2sEpL1c/o28KkgqHcp3kl82rnN4fDoBvWMvqxWve2TL4sEwL5ssZV+G/r+8ghqzElPmcvEEJ2bkaeGuuKl7/kFjMyFJrHzyAiSLnpuTasTGSZHLzwEbDiH7RUrCa2V8lBlKIV0H2pfXSPNc=,iv:HGmXTC1znAJZqBfpkwC+/y//V6l3XA5i6Gmpc652mZI=,tag:Bi1wDMn09UXKqGKdB7jRcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
