metrics: true

storage:
  type: sqlite
  path: /data/data.db

security:
  basic:
    username: admin
    password-bcrypt-base64: JDJ5JDA5JFBsWC5ySzdFMmswcWVJTG03ZEp1LmVpRXduZlVOSGQxS25uNUgyNXc3NGNKUFI3UGpPZUlT

ui:
  title: "Homelab"
  header: "Homelab"
  theme: dark

endpoints:
  - name: traefik-dashboard
    url: https://traefik.staging.lab.supermorphic.com
    interval: 30s
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    group: Infrastructure

  - name: argocd
    url: https://argocd.staging.lab.supermorphic.com
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    group: GitOps

  - name: grafana
    url: https://grafana.staging.lab.supermorphic.com/api/health
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY].database == ok"
    group: Observability

  - name: prometheus
    url: https://prometheus.staging.lab.supermorphic.com/-/healthy
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    group: Observability

  - name: longhorn
    url: https://longhorn.staging.lab.supermorphic.com
    interval: 2m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    group: Storage

  - name: homepage
    url: https://homepage.staging.lab.supermorphic.com
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    group: Dashboards

  - name: cert-manager-staging-api
    url: https://acme-v02.api.letsencrypt.org/
    interval: 10m
    conditions:
      - "[STATUS] == 200"
    group: External

  - name: kubernetes-api
    url: https://kubernetes.default.svc:443/livez
    interval: 1m
    client:
      insecure: true
      headers:
        Authorization: "Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
    conditions:
      - "[STATUS] == 200"
    group: Internal
