apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gatus.yaml
  - certificate.yaml
  - ingressroute.yaml
  - api-ingressroute.yaml

configMapGenerator:
  - name: gatus
    namespace: gatus-staging
    files:
      - config.yaml
    behavior: replace
    options:
      disableNameSuffixHash: true
