apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - gatus.yaml
  - certificate.yaml
  - ingressroute.yaml
generators:
  - ksops-generator.yaml