apiVersion: v1
kind: Secret
metadata:
    name: traefik-auth-credentials
    namespace: gatus-staging
stringData:
    TRAEFIK_BASIC_AUTH: ENC[AES256_GCM,data:D3wfjCyA8JU8l/Ax/GYWy3L5yPWp+OdOp1J1i+8nTJTVM1f/+w==,iv:OImB4aS8Je4IW35kspJPNKm00KmBXA9yF1HOqTnrD74=,tag:nqwTkDe9eIQtfgrnzfgBYw==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQno2dDE5U2tKMVUyemJC
            bW9XL1Q1dThVYjNBNkNEVCtQV3hra2xaMlhzCmxvbEV4NU11UzhTYlBiZHJNR3Mv
            T3cybHlBOGNNK2FqOVZybys4RmowODQKLS0tIEdCWCs1NEdka3VrQXRQSDB1Mi9R
            Wmt3aVNQRTh5clQ1MGxJNmdKNmxlYzAK+3fqeEJB6H1Hk5H4Vbn8y2W7qSnbTDZ6
            9VJFY5JmZRNTdUBIgXPhBF/k+sttfrQXv8AkqXPGJ6eXZZZdnV3UBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T07:09:23Z"
    mac: ENC[AES256_GCM,data:AKHNerHXaQal8UOpMGAh5/eckcbXduCEixifNrw2mSkHTArxoU/uVXQm7ZLe+yEab8+9R9Jwddj2vsgZoz2fhTMRf+W3U2F1UVCFXWoOZ+fop+dWuc9N3chdOI4SeKEJBjZnAd9+lylR96NlN3rUbq3+s2/Fs+kzyPNGynTqoc4=,iv:IHWlKCjxknF81EbPpEYHiO7l62uLNJhTwfmKklS7nrQ=,tag:RAJ+FzmsIsBcyQ4IZRXaEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
