apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager-staging
spec:
  encryptedData:
    api-token: AgAC9d6DXuuKvBMG5nSuN/NBZBOG97ZtcgmUarRiwbuoCHOjHlxhECBoZnyZt+hoYxnz7Ni/vaOX6SNiOMS7/Vug78qJyrImcDmLf0i4o5xbyveb6TVAtMMfkDjRU/UCUUH+zOH6SYOJivH1VNCzTEO5EPPglNSIWQjaDr6Lf1BzbFLo54AvdEz463UhnmHXPubxFJO17Ik+WtglMqDQtqH7SOZ10IEtzOrnMxmoP3J04CA+CT0ui4uQbCbxBtDUzbDeyLAl4GBR0eIoqwSv1zfh5i3QHGY1RFhfGf/srHSiZHbS1AIVN2CZZtb/8L7Fn4YP6QlJ2CzwceMiEMwYzPYjnvGa0xYylG6+Bm+WH5xvxwpIWSItWnLd1itdi+4xEStrNICNao0rGgIRjxFn/E5lt8u0gSQDCjOTcUQy1EaMomIdzQKkDcjxp82Fbni2NxMBAqB8qqCKIBDeBmPBQN5+1Xa1g0dYd9sw3wuVRSlYSgm94Hi1YVxiuC1XM+p3EaxnATh/V7/t1d5ItfCWIt1mCMkd3AloT/MJM5peZBs4DSFkuaKi/1nIV49FK+MsxVwy6MRmwgYbKinvojPmfSUbzZVJVYp6q/Yq2ijUDtoaRWHni6SuirsQk+6FIBAKGRIBv1hBuKPBnY5vWtuSISWFpa1tYRL1mcW/zNp4Kf4y68msBrVx68Ds/tSHaWM3LGdqYTH4Z/6TC5Xr3uTaO6xin6dKSslMUfh2gZ+XZAqjaCwC/sDJ24zq
  template:
    metadata:
      name: cloudflare-secret
      namespace: cert-manager-staging
    type: Opaque
