apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-noverify
  namespace: argocd-staging
spec:
  serverName: "argocd-server.argocd.svc.cluster.local"
  insecureSkipVerify: true
