apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/ksiggins/homelab-gitops.git
        revision: appsets
        directories:
          - path: infra/*
  template:
    metadata:
      name: '{{index .path.segments 1}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ksiggins/homelab-gitops.git
        targetRevision: appsets
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
