apiVersion: v1
kind: Secret
metadata:
  name: dashboard-auth
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  users: "YWRtaW46JGFwcjEkOXZsSUhPNHkkOXBQZnZmcXQybmhJNi5qbVREdVpKMAoK"
