apiVersion: v1
kind: Secret
metadata:
    name: dashboard-auth
    namespace: traefik-v2-prod
type: Opaque
data:
    users: ENC[AES256_GCM,data:nqg+DQgWdWK2rXkQPMUoOneDg5zK2OkP/1yuyrq83HeAMIOrNmKlmT9JJkPsgnd/LsCxkpRNyoFbxqYK,iv:ClMuk4yVICe3owdF6wOQ8T9OAr4jxfDOoBTkux12gTw=,tag:Qm4MG6pQIOn1OXLGFNaMMw==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeDZFdzlXejVHS3JkMG1j
            eGVCY2NLZ0hldEdHSVVacWRhKzI0ZDQ5ZjJNCll4cnFRbHFYc1R3c2d6aytBWUZh
            UjJrWVcvZ1g5Q1RYWHhvTG02RUw1ckEKLS0tIEQ3dHdESFBqdFNESkxGc2FFejFB
            NXZvZ2pCa0pkM3lxeFRQSzh3ZERFR0EKZaicxl4ysSptphWo8rhagCXT9dozkVEY
            3CnOGcvWTnzvpcj4wHmDLiiElblDRZ0+ttkEP5h4bDFi+Pi5iDpDzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T04:04:42Z"
    mac: ENC[AES256_GCM,data:2mFoFsyUtwg+bs18HOt8nVrD6kK3HhVuhH4WO28jFn6e367171stKPZUOtvw2Ngvzf4E8R2wwLJMk20MOELnUy8dHzLVwfKhCFA2MNcEzUqTMDr+AGpKAmWJMh6K528wucBO80ObHMuAb3fpBNBpmMSzBWNMbDDD+Ax3GHKDTs0=,iv:cfXXqvsG6bApqDhT0q9rKAC/cJeMLMSFTiRhoOFozWk=,tag:xMC6C88GQ4SjtsvUM7YiVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
