apiVersion: v1
kind: Secret
metadata:
    name: dashboard-auth
    namespace: traefik-v2-prod
type: Opaque
data:
    users: ENC[AES256_GCM,data:ZPAgGKmZ8uwffaVA+hX9EeHop0KJdhzAotbgiA4lAMgUEljeBYdlRh+Zh6SnIBMVNW2BSJQT80Q1oulk,iv:4h+zBsPz1OSmCgit7pfwHT+ce/An0rwlUcUvZZ7XPKo=,tag:lB5zNsO5dJohM1Zl0VfiDQ==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYVliWEttWG9aTFRveEs5
            T2FKWktHQm55K2cxVnVyQTJUZDBkdDQ5L0JRCmRXWlp3MkpkSjJPTWRNb1l6dXlz
            cVBReGpiTnA0V0pYY200SlByWkVkMlEKLS0tIG83NHdVU2cvSjY3Y3JXVDUxRFlw
            MEJjbFdnMUJVaUFmbjlQRjhhTm9oYmsKXitkIKb5sd2EebMt9/uFiLuBC/VyVHnc
            QEmTkTmINQpqeiUC9wOt85ZJKJX38YuqYajF+brxTwoQ/u39wZ1BKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T03:35:51Z"
    mac: ENC[AES256_GCM,data:nZu16wxiGfvIXLEMikfgspNFEjQg+R3yzR/XJJgJ3oegAcHEjbJQSi3Z/XhzUyjKkMUYlK8zNXiClBlyPrPKFNh0Sb+/KILOIfxfx1bSYhS8z4EfJ0O3GvYgymGIYrc4TbEOodLlQt3yW6eTU12YasVlQIL4QdYpFq+3gVsVa8M=,iv:ZhZXXpTjMgFbD1UCY+zurtS+gcvOv+1+F+CfL8o8s64=,tag:OdA1IUvs3NqWScQHsPUgCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
