deployment:
  replicas: 2

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    allowCrossNamespace: true

globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
