apiVersion: v1
kind: Secret
metadata:
  name: argocd-api-token
  namespace: homepage-staging
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "argocd/argocd-api-token"
type: Opaque
stringData:
  api-token: ""