apiVersion: v1
kind: Secret
metadata:
    name: gatus-admin-credentials
    namespace: homepage-staging
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:EYLRtyA=,iv:g3lipiEyL8z2SofxJZCiJFQkUbFLp3VsV8Z5HgV4LrA=,tag:JBTph0PbS128c0+yKKwBLg==,type:str]
    password: ENC[AES256_GCM,data:GAB9GC0iZgODKkmkRmJ4Rug6Ubjsobd1Ew+EMIEkY55GQwvKVFucPQ==,iv:rzG7bM+FoxCWNMEx+w11YRRQ4mtREUWPFYkUMiYho/s=,tag:+uRVjXdK48lWeOqL2FAviw==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTWdkTndkM3IwRjU2a01W
            OTZwWXdWRWlHY0JoL0lhMzRlR1VpWGFaSVdBCjFYaDI5N21KdXVxdVBocGRrZjdK
            cTJpQ2tBSDVpVlptYW84MnNtUElxWWMKLS0tIHVPWlJaZGpLOXE0MC8xamZFMVVY
            SjVVZ3ZvZ3pkL0c4N2Q4d2pxUTA4eEEKwg3MOateHsA6iCg5b/kTNi5najAmkimM
            HRY/z86EFB3vLLAKW/Uz3K+sUN3YzKtrRpszeZYALElfgd9BzJXbCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T05:35:47Z"
    mac: ENC[AES256_GCM,data:fNL+Mtmj/BaWVcy1ToolAmu7ANBkUeBtpPvE+7EX5CZTPxWR4OwE4E1+LjBeIEGiMeO2fbfLWz9rUvBphySx4LGkN9TqJ72phpME+1qrDRjMY2/OcWbJrQhNodcaiNlYDVTSAfQIdExjxWP2g2nhe9uz5l87pERC/kXt5kV/MMo=,iv:M25YCoWJwMnK75tTPtOtgyQhCYpOZxUS2FjrjcqLd5I=,tag:SEfSDMCRHlX7dM1NfmIanA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
