apiVersion: v1
kind: Secret
metadata:
    name: gatus-admin-credentials
    namespace: homepage-staging
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:uUOQPSQ=,iv:Z9OuOGD5hjDQMRoWayTrt154fSJCfauvP3QvHcz8zgM=,tag:LUCdAyBzwxr2lt9Oloa93A==,type:str]
    password: ENC[AES256_GCM,data:k7GqgoU/EMIcnjcSjnq+at3OEbBH0JBMlmuFwy7hY+Q0mT6JXnVW1A==,iv:3BI6OaOoxvzIzwDLoxo76BkamQ2hmugde6hoYJIicDc=,tag:QqQYb9aSR8DCtlomfUMBlg==,type:str]
sops:
    age:
        - recipient: age13r239sgyet9tarzzvmy03ddv9v2u7xq9gu60kg47v97mxw86cgpqa4qr2u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybEtQMW1GZUJBbmNvaEFF
            K2tGU2lnQ0RPUXVaMyt1NTZOTWFWNWN4NW1BCjRWUXNnMVM4cHNJamlrZG5DeFlx
            TXRiWW1TOEZxL2FnT0FOZWZaV3hDeTgKLS0tIHYvMjRCRFNSaUlMTjV0R3ZtMkFq
            TXkxajhzcmEyRnVkQXM0UHZhT3pTUm8KHU4Zl1vGqFFTaHVFKDt1FMNywwR0fU3V
            +uTRaUY5QhopRi2zrz+6sBsuVuL2Y2iLLFLNmM0qT4clfaDKohzMDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T05:28:47Z"
    mac: ENC[AES256_GCM,data:rI9GvQLTIMg1Npd3qrv4MDc92jhXan2W+ca7E6G3IMSP6ShVNnWiU4zF0vJLMqMYUezbngaSuxD3XYUUDqm0PgpS86vYxKyplCVXUKWdXF8XMt6Z2ZLyHtU/LQpBFbSOlkRC6ohasl2R9vk0RmEcyjjTtCRociNbuGA0y1WB6rc=,iv:oLKAzjFgN2qpvA8rGPNiM1MBtEUh6lK2lXIYFsHku3k=,tag:7CWaN447Y/zGU0ft4ktrRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
